version: '3.8'
services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest
    restart: always
    depends_on:
      - postgres
      - redis
      - backup
    env_file:
      - .env
      - .env.testnet

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      REDIS_PASSWORD: ''

  cors:
    build: ./docker-nginx-cors/
    container_name: cors
    restart: always
    depends_on:
      - nest
    ports:
      - '443:443'
      - '80:80'

  backup:
    build: ./filebase-backup/
    container_name: backup
    volumes:
      - ./filebase-backup/scripts:/scripts
      - ./filebase-backup/crontab:/crontab
    depends_on:
      - postgres
    env_file: .env
